name: Release to PyPI

on:
  schedule:
    # weekly on Sunday. This will 
    - cron: "4 23 * * 0"

  # as needed by clicking through the github actions UI
  workflow_dispatch:

# we do not want more than one release workflow executing at the same time, ever
concurrency:
  group: release
  # cancelling in the middle of a release would create incomplete releases
  # so cancel-in-progress is false
  cancel-in-progress: false

jobs:
  release:
    if: github.repository_owner == 'NickCrews'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.8"

      - uses: extractions/setup-just@v3
        env:
          just-version: "1.42.4"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump ibis version
        id: get-version
        run: echo "value=$(just set-version)" | tee -a "$GITHUB_OUTPUT"

      - name: build wheel and source dist
        run: uv build

      - name: publish wheel to pypi
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e

      - name: create GH release
        # even if publish to pypi failed, we want to create a release on GitHub
        if: always()
        run: gh release create v${{ steps.get-version.outputs.value }} dist/* --title "Release v${{ steps.get-version.outputs.value }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
